version: '3.8'
services:
  backend:
    build: .
    container_name: blog-backend
    ports:
      - "${BACKEND_PORT}:3000"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
