version: '3.8'
services:
  frontend:
    build:
      context: .
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    container_name: blog-frontend
    ports:
      - "${FRONTEND_PORT}:3001"
    env_file:
      - .env
    restart: always
    environment:
      - REACT_APP_API_URL=http://18.202.55.100:3000  
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s



    