global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mongo-exporter'
    static_configs:
      - targets: ['mongo-exporter:9216']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blod-db'
    static_configs:
      - targets: ['localhost:27017']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
